apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hello-python
  template:
    metadata:
      labels:
        name: hello-python
    spec:
      containers:
      - name: hello-python
        image: hello-python:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80  
      